{"uid":"98afaea830a26991","name":"test_create_order_note[guestuser_1_note]","fullName":"tests.backend.orders.test_create_order_notes#test_create_order_note","historyId":"f6823c01634bc43a83478852c225929a","time":{"start":1758007416321,"stop":1758007416321,"duration":0},"description":"Test creating one or multiple order notes for a given user type.\n\nArgs:\n    order_notes_setup (dict): Fixture providing DAOs, helpers, product ID, note text, and order tracking.\n    user_type (str): 'guest_user' or 'registered_user'.\n    quantity (int): Number of notes to create.\n","descriptionHtml":"<p>Test creating one or multiple order notes for a given user type.</p>\n<p>Args:<br />\norder_notes_setup (dict): Fixture providing DAOs, helpers, product ID, note text, and order tracking.<br />\nuser_type (str): 'guest_user' or 'registered_user'.<br />\nquantity (int): Number of notes to create.</p>\n","status":"broken","statusMessage":"RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods","statusTrace":"@pytest.fixture(scope=\"module\")\n    def order_notes_setup():\n        \"\"\"Set up DAOs, helpers, a random product, default note text, and track created orders.\"\"\"\n        orders_api_helpers = OrdersAPIHelper()\n        products_dao = ProductsDAO()\n        customers_dao = CustomersDAO()\n        generic_orders_helper = GenericOrdersHelper()\n    \n        # fetch random product from db\n>       product = products_dao.get_random_product_from_db(qty=1)[0]\n\ntests/backend/orders/test_create_order_notes.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/dao/products_dao.py:40: in get_random_product_from_db\n    rs_sql = self.db_helper.execute_select(sql)\nsrc/utilities/dbUtility.py:31: in execute_select\n    conn = self.create_connection()\nsrc/utilities/dbUtility.py:23: in create_connection\n    connection = pymysql.connect(host=self.host, user=self.creds['db_user'],\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:361: in __init__\n    self.connect()\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:669: in connect\n    self._request_authentication()\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:979: in _request_authentication\n    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py:267: in caching_sha2_password_auth\n    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npassword = b'SpecialStudentsSecret', salt = b'%P;-4y\\x03\\x15.A\\rr\\x7f\\x18=WXH h'\npublic_key = b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmE7rN2b1SK+cHlbBJuhy\\n7WnyqChNyu7BrMutBWtlMO...EozxYH9BW+KJ23\\nvx4a0Hrs6Ui6XNKiYmsK9l/PwEwYt3phoWR0RAh27OM12+mxaNwalSUs0uosqNFr\\nNwIDAQAB\\n-----END PUBLIC KEY-----\\n'\n\n    def sha2_rsa_encrypt(password, salt, public_key):\n        \"\"\"Encrypt password with salt and public_key.\n    \n        Used for sha256_password and caching_sha2_password.\n        \"\"\"\n        if not _have_cryptography:\n>           raise RuntimeError(\n                \"'cryptography' package is required for sha256_password or\"\n                + \" caching_sha2_password auth methods\"\n            )\nE           RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods\n\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py:144: RuntimeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"order_notes_setup","time":{"start":1758007416322,"stop":1758007416394,"duration":72},"status":"broken","statusMessage":"RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/Ecommerce-Pytest-Framework/Ecommerce-Pytest-Framework/demostore_automation/tests/backend/orders/test_create_order_notes.py\", line 24, in order_notes_setup\n    product = products_dao.get_random_product_from_db(qty=1)[0]\n              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n  File \"/home/runner/work/Ecommerce-Pytest-Framework/Ecommerce-Pytest-Framework/demostore_automation/src/dao/products_dao.py\", line 40, in get_random_product_from_db\n    rs_sql = self.db_helper.execute_select(sql)\n  File \"/home/runner/work/Ecommerce-Pytest-Framework/Ecommerce-Pytest-Framework/demostore_automation/src/utilities/dbUtility.py\", line 31, in execute_select\n    conn = self.create_connection()\n  File \"/home/runner/work/Ecommerce-Pytest-Framework/Ecommerce-Pytest-Framework/demostore_automation/src/utilities/dbUtility.py\", line 23, in create_connection\n    connection = pymysql.connect(host=self.host, user=self.creds['db_user'],\n                                 password=self.creds['db_password'],\n                                 port=self.port)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py\", line 361, in __init__\n    self.connect()\n    ~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py\", line 669, in connect\n    self._request_authentication()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py\", line 979, in _request_authentication\n    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py\", line 267, in caching_sha2_password_auth\n    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py\", line 144, in sha2_rsa_encrypt\n    raise RuntimeError(\n    ...<2 lines>...\n    )\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Test creating one or multiple order notes for a given user type.\n\nArgs:\n    order_notes_setup (dict): Fixture providing DAOs, helpers, product ID, note text, and order tracking.\n    user_type (str): 'guest_user' or 'registered_user'.\n    quantity (int): Number of notes to create.\n","status":"broken","statusMessage":"RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods","statusTrace":"@pytest.fixture(scope=\"module\")\n    def order_notes_setup():\n        \"\"\"Set up DAOs, helpers, a random product, default note text, and track created orders.\"\"\"\n        orders_api_helpers = OrdersAPIHelper()\n        products_dao = ProductsDAO()\n        customers_dao = CustomersDAO()\n        generic_orders_helper = GenericOrdersHelper()\n    \n        # fetch random product from db\n>       product = products_dao.get_random_product_from_db(qty=1)[0]\n\ntests/backend/orders/test_create_order_notes.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/dao/products_dao.py:40: in get_random_product_from_db\n    rs_sql = self.db_helper.execute_select(sql)\nsrc/utilities/dbUtility.py:31: in execute_select\n    conn = self.create_connection()\nsrc/utilities/dbUtility.py:23: in create_connection\n    connection = pymysql.connect(host=self.host, user=self.creds['db_user'],\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:361: in __init__\n    self.connect()\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:669: in connect\n    self._request_authentication()\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/connections.py:979: in _request_authentication\n    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py:267: in caching_sha2_password_auth\n    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npassword = b'SpecialStudentsSecret', salt = b'%P;-4y\\x03\\x15.A\\rr\\x7f\\x18=WXH h'\npublic_key = b'-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmE7rN2b1SK+cHlbBJuhy\\n7WnyqChNyu7BrMutBWtlMO...EozxYH9BW+KJ23\\nvx4a0Hrs6Ui6XNKiYmsK9l/PwEwYt3phoWR0RAh27OM12+mxaNwalSUs0uosqNFr\\nNwIDAQAB\\n-----END PUBLIC KEY-----\\n'\n\n    def sha2_rsa_encrypt(password, salt, public_key):\n        \"\"\"Encrypt password with salt and public_key.\n    \n        Used for sha256_password and caching_sha2_password.\n        \"\"\"\n        if not _have_cryptography:\n>           raise RuntimeError(\n                \"'cryptography' package is required for sha256_password or\"\n                + \" caching_sha2_password auth methods\"\n            )\nE           RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods\n\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pymysql/_auth.py:144: RuntimeError","steps":[],"attachments":[{"uid":"537fbc4322b4afc6","name":"log","source":"537fbc4322b4afc6.txt","type":"text/plain","size":145}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"tag","value":"ordernotes"},{"name":"tag","value":"ecomnotes"},{"name":"tag","value":"ecomnotes1"},{"name":"parentSuite","value":"tests.backend.orders"},{"name":"suite","value":"test_create_order_notes"},{"name":"host","value":"runnervmf4ws1"},{"name":"thread","value":"2079-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.backend.orders.test_create_order_notes"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"quantity","value":"1"},{"name":"user_type","value":"'guest_user'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["ordernotes","ecomnotes1","ecomnotes"]},"source":"98afaea830a26991.json","parameterValues":["1","'guest_user'"]}